---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  path: {{ .Values.vaultSecretPath }}/{{ .Values.namespace }}
  type: Opaque
