vaultSecretPath: secret/phalanx/summit
manager:
  frontend:
    image:
      repository: ts-dockerhub.lsst.org/love-manager
      tag: c0039.008
      pullPolicy: Always
    env:
      SERVER_URL: summit-lsp.lsst.codes
      OLE_API_HOSTNAME: summit-lsp.lsst.codes
      AUTH_LDAP_1_SERVER_URI: ldap://ipa1.cp.lsst.org
      AUTH_LDAP_2_SERVER_URI: ldap://ipa2.cp.lsst.org
      AUTH_LDAP_3_SERVER_URI: ldap://ipa3.cp.lsst.org
      DB_HOST: postgresdb01.cp.lsst.org
      LOVE_SITE: summit
    autoscaling:
      enabled: true
      minReplicas: 10
      maxReplicas: 50
      targetCPUUtilizationPercentage: 80
      scaleDownPolicy:
        policies:
        - type: Pods
          value: 2
          periodSeconds: 120
        - type: Percent
          value: 10
          periodSeconds: 120
        selectPolicy: Min
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 20
      periodSeconds: 10
  producers:
  - name: general
    image:
      repository: ts-dockerhub.lsst.org/love-manager
      tag: c0039.008
      pullPolicy: Always
      nexus3: pull-secret
    env:
      AUTH_LDAP_1_SERVER_URI: ldap://ipa1.cp.lsst.org
      AUTH_LDAP_2_SERVER_URI: ldap://ipa2.cp.lsst.org
      AUTH_LDAP_3_SERVER_URI: ldap://ipa3.cp.lsst.org
      COMMANDER_HOSTNAME: love-commander-service
      COMMANDER_PORT: 5000
      DB_ENGINE: postgresql
      DB_HOST: postgresdb01.cp.lsst.org
      DB_NAME: love
      DB_PORT: 5432
      DB_USER: love
      HEARTBEAT_QUERY_COMMANDER: false
      JIRA_API_HOSTNAME: rubinobs.atlassian.net
      JIRA_PROJECT_ID: 10063
      LOVE_SITE: summit
      OLE_API_HOSTNAME: summit-lsp.lsst.codes
      REDIS_CONFIG_CAPACITY: 5000
      REDIS_CONFIG_EXPIRY: 5
      REDIS_HOST: love-manager-redis-service
      REMOTE_STORAGE: true
      SERVER_URL: summit-lsp.lsst.codes
      URL_SUBPATH: /love
    envSecrets:
      SECRET_KEY: manager-secret-key
      PROCESS_CONNECTION_PASS: process-connection-pass
      ADMIN_USER_PASS: admin-user-pass
      USER_USER_PASS: user-user-pass
      CMD_USER_PASS: cmd-user-pass
      AUTHLIST_USER_PASS: authlist-user-pass
      AUTH_LDAP_BIND_PASSWORD: auth-ldap-bind-password
      DB_PASS: db-pass
      REDIS_PASS: redis-pass
    replicas: 10
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 25
      targetCPUUtilizationPercentage: 50
      scaleDownPolicy:
        policies:
        - type: Pods
          value: 2
          periodSeconds: 120
        - type: Percent
          value: 10
          periodSeconds: 120
        selectPolicy: Min
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 20
      periodSeconds: 10
  - name: queue
    image:
      repository: ts-dockerhub.lsst.org/love-manager
      tag: c0039.008
      pullPolicy: Always
      nexus3: pull-secret
    env:
      AUTH_LDAP_1_SERVER_URI: ldap://ipa1.cp.lsst.org
      AUTH_LDAP_2_SERVER_URI: ldap://ipa2.cp.lsst.org
      AUTH_LDAP_3_SERVER_URI: ldap://ipa3.cp.lsst.org
      COMMANDER_HOSTNAME: love-commander-service
      COMMANDER_PORT: 5000
      DB_ENGINE: postgresql
      DB_HOST: postgresdb01.cp.lsst.org
      DB_NAME: love
      DB_PORT: 5432
      DB_USER: love
      HEARTBEAT_QUERY_COMMANDER: false
      JIRA_API_HOSTNAME: rubinobs.atlassian.net
      JIRA_PROJECT_ID: 10063
      LOVE_SITE: summit
      OLE_API_HOSTNAME: summit-lsp.lsst.codes
      REDIS_CONFIG_CAPACITY: 5000
      REDIS_CONFIG_EXPIRY: 5
      REDIS_HOST: love-manager-redis-service
      REMOTE_STORAGE: true
      SERVER_URL: summit-lsp.lsst.codes
      URL_SUBPATH: /love
    envSecrets:
      SECRET_KEY: manager-secret-key
      PROCESS_CONNECTION_PASS: process-connection-pass
      ADMIN_USER_PASS: admin-user-pass
      USER_USER_PASS: user-user-pass
      CMD_USER_PASS: cmd-user-pass
      AUTHLIST_USER_PASS: authlist-user-pass
      AUTH_LDAP_BIND_PASSWORD: auth-ldap-bind-password
      DB_PASS: db-pass
      REDIS_PASS: redis-pass
    replicas: 3
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 25
      targetCPUUtilizationPercentage: 50
      scaleDownPolicy:
        policies:
        - type: Pods
          value: 2
          periodSeconds: 120
        - type: Percent
          value: 10
          periodSeconds: 120
        selectPolicy: Min
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 20
      periodSeconds: 10
  - name: m1m3
    image:
      repository: ts-dockerhub.lsst.org/love-manager
      tag: c0039.008
      pullPolicy: Always
      nexus3: pull-secret
    env:
      AUTH_LDAP_1_SERVER_URI: ldap://ipa1.cp.lsst.org
      AUTH_LDAP_2_SERVER_URI: ldap://ipa2.cp.lsst.org
      AUTH_LDAP_3_SERVER_URI: ldap://ipa3.cp.lsst.org
      COMMANDER_HOSTNAME: love-commander-service
      COMMANDER_PORT: 5000
      DB_ENGINE: postgresql
      DB_HOST: postgresdb01.cp.lsst.org
      DB_NAME: love
      DB_PORT: 5432
      DB_USER: love
      HEARTBEAT_QUERY_COMMANDER: false
      JIRA_API_HOSTNAME: rubinobs.atlassian.net
      JIRA_PROJECT_ID: 10063
      LOVE_SITE: summit
      OLE_API_HOSTNAME: summit-lsp.lsst.codes
      REDIS_CONFIG_CAPACITY: 5000
      REDIS_CONFIG_EXPIRY: 5
      REDIS_HOST: love-manager-redis-service
      REMOTE_STORAGE: true
      SERVER_URL: summit-lsp.lsst.codes
      URL_SUBPATH: /love
    envSecrets:
      SECRET_KEY: manager-secret-key
      PROCESS_CONNECTION_PASS: process-connection-pass
      ADMIN_USER_PASS: admin-user-pass
      USER_USER_PASS: user-user-pass
      CMD_USER_PASS: cmd-user-pass
      AUTHLIST_USER_PASS: authlist-user-pass
      AUTH_LDAP_BIND_PASSWORD: auth-ldap-bind-password
      DB_PASS: db-pass
      REDIS_PASS: redis-pass
    replicas: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 25
      targetCPUUtilizationPercentage: 50
      scaleDownPolicy:
        policies:
        - type: Pods
          value: 2
          periodSeconds: 120
        - type: Percent
          value: 10
          periodSeconds: 120
      selectPolicy: Min
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 20
      periodSeconds: 10
redis:
  image:
    repository: redis
    tag: '7'
    pullPolicy: IfNotPresent
  config: |
    timeout 60
viewBackup:
  enabled: true
  image:
    repository: ts-dockerhub.lsst.org/love-view-backup
    tag: c0039.000
    pullPolicy: Always
  schedule: 0 12 * * *
