secret_path: summit-lsp.lsst.codes
manager:
  frontend:
    image:
      repository: ts-dockerhub.lsst.org/love-manager
      tag: c0036.003
      pullPolicy: Always
      nexus3: nexus3-docker
    env:
      SERVER_URL: summit-lsp.lsst.codes
      OLE_API_HOSTNAME: summit-lsp.lsst.codes
      AUTH_LDAP_1_SERVER_URI: ldap://ipa1.cp.lsst.org
      AUTH_LDAP_2_SERVER_URI: ldap://ipa2.cp.lsst.org
      AUTH_LDAP_3_SERVER_URI: ldap://ipa3.cp.lsst.org
      DB_HOST: postgresdb01.cp.lsst.org
      LOVE_SITE: summit
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 50
      targetCPUUtilizationPercentage: 50
      scaleDownPolicy:
        policies:
        - type: Pods
          value: 2
          periodSeconds: 120
        - type: Percent
          value: 10
          periodSeconds: 120
        selectPolicy: Min
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 20
      periodSeconds: 10
  producers:
    image:
      repository: ts-dockerhub.lsst.org/love-manager
      tag: c0036.003
      pullPolicy: Always
      nexus3: nexus3-docker
    env:
      SERVER_URL: summit-lsp.lsst.codes
      OLE_API_HOSTNAME: summit-lsp.lsst.codes
      AUTH_LDAP_1_SERVER_URI: ldap://ipa1.cp.lsst.org
      AUTH_LDAP_2_SERVER_URI: ldap://ipa2.cp.lsst.org
      AUTH_LDAP_3_SERVER_URI: ldap://ipa3.cp.lsst.org
      DB_HOST: postgresdb01.cp.lsst.org
      LOVE_SITE: summit
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 50
      targetCPUUtilizationPercentage: 50
      scaleDownPolicy:
        policies:
        - type: Pods
          value: 2
          periodSeconds: 120
        - type: Percent
          value: 10
          periodSeconds: 120
        selectPolicy: Min
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 20
      periodSeconds: 10
redis:
  image:
    repository: redis
    tag: '7'
    pullPolicy: IfNotPresent
  config: |
    timeout 60
viewBackup:
  enabled: true
  image:
    repository: ts-dockerhub.lsst.org/love-view-backup
    tag: c0036.000
    pullPolicy: Always
    nexus3: nexus3-docker
  schedule: 0 12 * * *
