namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/mtaos
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-mtaos.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtaos.log
shmemDir: /run/ospl
butlerSecret:
  containerPath: &bS-cP /home/saluser/.lsst
  dbUser: oods
secretPermFixer:
- name: butler-secret
  containerPath: *bS-cP
nfsMountpoint:
- name: comcam-gen3-data
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: nfs3.cp.lsst.org
  serverPath: /comcam/repo/LSSTComCam
- name: comcam-gen3-data-temp
  containerPath: /data/lsstdata/base/comcam
  readOnly: true
  server: nfs3.cp.lsst.org
  serverPath: /comcam/lsstdata/base/comcam
- name: comcam-data
  containerPath: /readonly/lsstdata/comcam
  readOnly: true
  server: nfs3.cp.lsst.org
  serverPath: /comcam/lsstdata
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs1.cp.lsst.org
  serverPath: /project
osplVersion: V6.10.4
