nfsMountpoint:
- name: comcam-gen3-butler
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.tu.lsst.org
  serverPath: /repo/LSSTComCam
- name: comcam-gen3-oods
  containerPath: /data/lsstdata/TTS/comcam
  readOnly: true
  server: comcam-archiver.tu.lsst.org
  serverPath: /lsstdata/TTS/comcam
- name: scratch
  containerPath: /scratch
  readOnly: false
  server: nfs-scratch.tu.lsst.org
  serverPath: /scratch
- name: obs-env
  containerPath: /net/obs-env
  readOnly: true
  server: nfs-obsenv.tu.lsst.org
  serverPath: /obs-env
