namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/mthexapod
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-mtcamhexapod.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtcamhexapod.log
  RUN_ARG: --simulate 1
shmemDir: /run/ospl
osplVersion: V6.10.4
