namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/ccoods
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  OSPL_INFOFILE: /tmp/ospl-info-ccoods.log
  OSPL_ERRORFILE: /tmp/ospl-error-ccoods.log
  CTRL_OODS_CONFIG_FILE: /etc/ccoods.yaml
shmemDir: /run/ospl
osplVersion: V6.10.4
butlerSecret:
  containerPath: &bS-cP /home/saluser/.lsst
  dbUser: oods
secretPermFixer:
- name: butler-secret
  containerPath: *bS-cP
nfsMountpoint:
- name: comcam-gen3-butler
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.tu.lsst.org
  serverPath: /repo/LSSTComCam
- name: comcam-oods-data
  containerPath: /data
  readOnly: false
  server: comcam-archiver.tu.lsst.org
  serverPath: /data
configfile:
  path: /etc
  filename: ccoods.yaml
  content: |
    defaultInterval: &interval
        days: 0
        hours: 0
        minutes: 0
        seconds: 0

    ingesterClass:
        ingesterType: lsst.ctrl.oods.fileIngester
        ingesterName : FileIngester

    ingester:
        imageStagingDirectory: /data/staging/comcam/oods
        butlers:
            - butler:
                class:
                    import : lsst.ctrl.oods.fileAttendant
                    name : FileAttendant
                instrument: lsst.obs.lsst.LsstComCam
                stagingDirectory : /data/lsstdata/TTS/comcam/oods/gen3butler/raw
                badFileDirectory: /data/lsstdata/TTS/comcam/oods/gen3butler/badfiles
                repoDirectory : /repo/LSSTComCam
                collections:
                    - LSSTComCam/raw/all
                cleanCollections:
                    - collection: LSSTComCam/raw/all
                      filesOlderThan:
                          <<: *interval
                          days: 30
                scanInterval:
                    <<: *interval
                    hours: 1
        batchSize: 20
        scanInterval:
            <<: *interval
            seconds: 2

    cacheCleaner:
        # ONLY clean out empty directories here, never files
        clearEmptyDirectories:
            -  /data/lsstdata/TTS/comcam/oods/gen3butler/raw
        # clean out empty directories and old files from these directories
        clearEmptyDirectoriesAndOldFiles:
            - /data/lsstdata/TTS/comcam/oods/gen3butler/badfiles
            - /data/staging/comcam/oods
            - /data/staging/comcam/camera
        scanInterval:
            <<: *interval
            hours: 1
        filesOlderThan:
            <<: *interval
            days: 31
        directoriesEmptyForMoreThan:
            <<: *interval
            days: 2
