namespace: auxtel
image:
  repository: ts-dockerhub.lsst.org/atdometrajectory
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-atdometrajectory.log
  OSPL_ERRORFILE: /tmp/ospl-error-atdometrajectory.log
shmemDir: /run/ospl
osplVersion: V6.10.4
