namespace: lsstcam
image:
  repository: ts-dockerhub.lsst.org/mtoods
  tag: m0001
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: base
  OSPL_INFOFILE: /tmp/ospl-info-mtoods.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtoods.log
  CTRL_OODS_CONFIG_FILE: /etc/mtoods.yaml
  AWS_ACCESS_KEY_ID: oods-lsstcam
  AWS_ENDPOINT_URL: https://s3-butler.ls.lsst.org
  LSST_KAFKA_SECURITY_USERNAME: ts-salkafka
  PYTHONASYNCIODEBUG: 1
envSecrets:
- name: AWS_SECRET_ACCESS_KEY
  secretKey: oods-lsstcam-secret-key
- name: LSST_KAFKA_SECURITY_PASSWORD
  secretKey: ts-salkafka-password
shmemDir: /run/ospl
osplVersion: V6.10.4
butlerSecret:
  containerPath: &bS-cP /home/saluser/.lsst
  dbUser: oods
secretPermFixer:
- name: butler-secret
  containerPath: *bS-cP
configfile:
  path: /etc
  filename: mtoods.yaml
  content: |
    defaultInterval: &interval
        days: 0
        hours: 0
        minutes: 0
        seconds: 0

    ingester:
        kafka:
            brokers:
                - sasquatch-kafka-brokers.sasquatch:9092
            topics:
                - lsst.s3.raw.lsstcam
            group_id: MTOODS-S3
            max_messages: 10
        butlers:
            - butler:
                instrument: lsst.obs.lsst.LsstCam
                class:
                    import : lsst.ctrl.oods.messageAttendant
                    name : MessageAttendant
                repoDirectory : s3://rubinobs-butler-lsstcam
                collections:
                    - LSSTCam/raw/all
                scanInterval:
                    <<: *interval
                    seconds: 10
                filesOlderThan:
                    <<: *interval
                    seconds: 30
        batchSize: 20
