image:
  repository: ts-dockerhub.lsst.org/rubintv-broadcaster
  tag: c0027
  pullPolicy: Always
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
scripts:
- runImExaminer.py
- runIsrRunner.py
- runMonitor.py
- runMountTorquePlotter.py
- runSpecExaminer.py
- runAllSky.py
- runMetadataServer.py
- runBackgroundService.py
credentialFile: google_write_creds
vaultPrefixPath: secret/k8s_operator/summit-lsp.lsst.codes
pullSecretsPath: ts/software/nexus3-docker
credentialSecretsPath: rubintv-broadcaster
butlerSecret:
  key: butler-secret
  containerPath: /home/saluser/.lsst
  dbUser: oods
imagePullSecrets:
- name: rubintv-broadcaster-pull-secret
nfsMountpoint:
- name: auxtel-gen3-data
  containerPath: /repo/LATISS
  readOnly: false
  server: auxtel-archiver.cp.lsst.org
  serverPath: /repo/LATISS
- name: comcam-gen3-data
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.cp.lsst.org
  serverPath: /repo/LSSTComCam
- name: auxtel-data
  containerPath: /readonly/lsstdata/auxtel
  readOnly: true
  server: auxtel-archiver.cp.lsst.org
  serverPath: /lsstdata
- name: comcam-data
  containerPath: /readonly/lsstdata/comcam
  readOnly: true
  server: comcam-archiver.cp.lsst.org
  serverPath: /lsstdata
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs1.cp.lsst.org
  serverPath: /project
- name: auxtel-gen3-data-temp
  containerPath: /data/lsstdata/base/auxtel
  readOnly: true
  server: auxtel-archiver.cp.lsst.org
  serverPath: /lsstdata/base/auxtel
- name: comcam-gen3-data-temp
  containerPath: /data/lsstdata/base/comcam
  readOnly: true
  server: comcam-archiver.cp.lsst.org
  serverPath: /lsstdata/base/comcam
- name: allsky-data
  containerPath: /data/allsky
  readOnly: true
  server: auxtel-archiver.cp.lsst.org
  serverPath: /allsky
