namespace: obssys
image:
  repository: ts-dockerhub.lsst.org/scriptqueue
  tag: c0039
  pullPolicy: Always
env:
  USER_USERNAME: user
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-ocsqueue.log
  OSPL_ERRORFILE: /tmp/ospl-error-ocsqueue.log
  RUN_ARG: 3 --state enabled
  S3_ENDPOINT_URL: https://s3.tu.lsst.org
  IMAGE_SERVER_URL: http://comcam-mcm.tu.lsst.org
envSecrets:
- name: USER_USER_PASS
  secretKey: user-user-pass
- name: AWS_ACCESS_KEY_ID
  secretKey: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  secretKey: aws-secret-access-key
- name: MYS3_ACCESS_KEY
  secretKey: aws-access-key-id
- name: MYS3_SECRET_KEY
  secretKey: aws-secret-access-key
shmemDir: /run/ospl
osplVersion: V6.10.4
butlerSecret:
  containerPath: &bS-cP /home/saluser/.lsst
  dbUser: oods
secretPermFixer:
- name: butler-secret
  containerPath: *bS-cP
nfsMountpoint:
- name: auxtel-gen3-butler
  containerPath: /repo/LATISS
  readOnly: false
  server: nfs-auxtel.tu.lsst.org
  serverPath: /auxtel/repo/LATISS
- name: auxtel-gen3-oods
  containerPath: /data/lsstdata/TTS/auxtel
  readOnly: true
  server: nfs-auxtel.tu.lsst.org
  serverPath: /auxtel/lsstdata/TTS/auxtel
- name: comcam-gen3-butler
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.tu.lsst.org
  serverPath: /repo/LSSTComCam
- name: comcam-gen3-oods
  containerPath: /data/lsstdata/TTS/comcam
  readOnly: true
  server: comcam-archiver.tu.lsst.org
  serverPath: /lsstdata/TTS/comcam
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs-project.tu.lsst.org
  serverPath: /project
- name: obs-env
  containerPath: /net/obs-env
  readOnly: true
  server: nfs-obsenv.tu.lsst.org
  serverPath: /obs-env
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: csc
          operator: In
          values:
          - atqueue
          - mtqueue
          - ocsqueue
      topologyKey: kubernetes.io/hostname
