namespace: obssys
image:
  repository: ts-dockerhub.lsst.org/scriptqueue
  tag: c0039
  pullPolicy: Always
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-mtqueue.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtqueue.log
  RUN_ARG: 3 --state enabled
  S3_ENDPOINT_URL: https://s3.cp.lsst.org
  IMAGE_SERVER_URL: http://ccs.lsst.org
shmemDir: /run/ospl
osplVersion: V6.10.4
butlerSecret:
  containerPath: &bS-cP /home/saluser/.lsst
  dbUser: oods
secretPermFixer:
- name: butler-secret
  containerPath: *bS-cP
nfsMountpoint:
- name: auxtel-gen3-data
  containerPath: /repo/LATISS
  readOnly: false
  server: nfs-auxtel.cp.lsst.org
  serverPath: /auxtel/repo/LATISS
- name: auxtel-gen3-data-temp
  containerPath: /data/lsstdata/base/auxtel
  readOnly: true
  server: nfs-auxtel.cp.lsst.org
  serverPath: /auxtel/lsstdata/base/auxtel
- name: auxtel-data
  containerPath: /readonly/lsstdata/auxtel
  readOnly: true
  server: nfs-auxtel.cp.lsst.org
  serverPath: /auxtel/lsstdata
- name: comcam-gen3-data
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: nfs3.cp.lsst.org
  serverPath: /comcam/repo/LSSTComCam
- name: comcam-gen3-data-temp
  containerPath: /data/lsstdata/base/comcam
  readOnly: true
  server: nfs3.cp.lsst.org
  serverPath: /comcam/lsstdata/base/comcam
- name: comcam-data
  containerPath: /readonly/lsstdata/comcam
  readOnly: true
  server: nfs3.cp.lsst.org
  serverPath: /comcam/lsstdata
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs1.cp.lsst.org
  serverPath: /project
- name: obs-env
  containerPath: /net/obs-env
  readOnly: true
  server: nfs-obsenv.cp.lsst.org
  serverPath: /obs-env
envSecrets:
- name: AWS_ACCESS_KEY_ID
  secretKey: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  secretKey: aws-secret-access-key
- name: MYS3_ACCESS_KEY
  secretKey: aws-access-key-id
- name: MYS3_SECRET_KEY
  secretKey: aws-secret-access-key
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: csc
          operator: In
          values:
          - atqueue
          - mtqueue
          - ocsqueue
      topologyKey: kubernetes.io/hostname
