image:
  repository: ts-dockerhub.lsst.org/scriptqueue
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_DDS_ENABLE_AUTHLIST: 1
  OSPL_INFOFILE: /tmp/ospl-info-mtqueue.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtqueue.log
  RUN_ARG: 1 --state enabled
shmemDir: /run/ospl
osplVersion: V6.10.4
butlerSecret:
  containerPath: /home/saluser/.lsst
  dbUser: oods
nfsMountpoint:
- name: auxtel-gen3-butler
  containerPath: /repo/LATISS
  readOnly: false
  server: auxtel-archiver.tu.lsst.org
  serverPath: /repo/LATISS
- name: auxtel-gen3-oods
  containerPath: /data/lsstdata/TTS/auxtel
  readOnly: true
  server: auxtel-archiver.tu.lsst.org
  serverPath: /lsstdata/TTS/auxtel
- name: comcam-gen3-butler
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.tu.lsst.org
  serverPath: /repo/LSSTComCam
- name: comcam-gen3-oods
  containerPath: /data/lsstdata/TTS/comcam
  readOnly: true
  server: comcam-archiver.tu.lsst.org
  serverPath: /lsstdata/TTS/comcam
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs-project.tu.lsst.org
  serverPath: /project
