env: tucson-teststand
namespace: maintel
cscs:
  - mtaos
  - mtptg
  - mtcamhexapod
  - mtm2hexapod
  - mtmount
  - mtrotator
  - mtdome
  - mtdometrajectory
  - mtm2
  - ccheaderservice
  - ccoods
  - mtaircompressor1
  - mtaircompressor2
  - lasertracker1
isSim:
  - mtcamhexapod
  - mtm2hexapod
  - mtmount
  - mtrotator
  - mtdome
  - mtm2
  - mtaircompressor1
  - mtaircompressor2
  - lasertracker1
