domainId: 0
waterMarksWhcAdaptive: false
ddsi2TracingEnabled: true
ddsi2TracingLogfile: ddsi2.log
durabilityServiceTracingEnabled: true
durabilityServiceTracingLogfile: durability.log
namespaces:
  - ospl-daemon
  - kafka-producers
  - lsstcam
