vaultPathPrefix: secret/phalanx/summit-lsp
secrets:
  ospl-daemon: ""
  kafka-producers: "calsys"
  auxtel: "auxtel"
  calsys: "calsys"
  dds-test: ""
  eas: "eas"
  love: ""
  maintel: "simonyitel"
  obssys: "obssys"
