# -- List of namespaces to create for the Kubernetes cluster.
namespaces:
  - auxtel
  - calsys
  - eas
  - love
  - maintel
  - obssys
  - kafka-producers
  - ospl-daemon
  - dds-test
# -- Site-specific Vault path for secrets.
vaultPathPrefix: ""
# -- This section holds secret specifications.
# This is a dictionary object that uses the following convention:
# namespace: "secret_name" if a secret is needed
# namespace: "" if a secret is not needed
# Pull secrets are created by default.
secrets: {}
