namespace: love
image:
  repository: ts-dockerhub.lsst.org/love-commander
  tag: c0037.000
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: summit
  S3_ENDPOINT_URL: https://s3.cp.lsst.org
  S3_INSTANCE: cp
  OSPL_INFOFILE: /tmp/ospl-info-love-commander.log
  OSPL_ERRORFILE: /tmp/ospl-error-love-commander.log
envSecrets:
- name: AWS_ACCESS_KEY_ID
  secretKey: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  secretKey: aws-secret-access-key
- name: MYS3_ACCESS_KEY
  secretKey: aws-access-key-id
- name: MYS3_SECRET_KEY
  secretKey: aws-secret-access-key
shmemDir: /run/ospl
osplVersion: V6.10.4
service:
  use: true
  port: 5000
  type: ClusterIP
