namespace: auxtel
image:
  repository: ts-dockerhub.lsst.org/atmcs_sim
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-atmcs.log
  OSPL_ERRORFILE: /tmp/ospl-error-atmcs.log
shmemDir: /run/ospl
osplVersion: V6.10.4
