image:
  repository: ts-dockerhub.lsst.org/dmocps
  tag: c0037
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: base
  LSST_SITE: base
  OSPL_INFOFILE: /tmp/ospl-info-raocps.log
  OSPL_ERRORFILE: /tmp/ospl-error-raocps.log
  RUN_ARG: 101
shmemDir: /run/ospl
osplVersion: V6.10.4
envSecrets:
- name: REDIS_PASSWORD
  secretName: rubintv-secrets
  secretKey: redis-password
