namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/headerservice
  tag: c0037
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: base
  LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
  URL_SPEC: --lfa_mode s3 --s3instance ls
  S3_ENDPOINT_URL: https://s3.ls.lsst.org
  TSTAND_HEADERSERVICE: BASE
  CAMERA: mt
  OSPL_INFOFILE: /tmp/ospl-info-mtheaderservice.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtheaderservice.log
envSecrets:
- name: AWS_ACCESS_KEY_ID
  secretKey: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  secretKey: aws-secret-access-key
- name: MYS3_ACCESS_KEY
  secretKey: aws-access-key-id
- name: MYS3_SECRET_KEY
  secretKey: aws-secret-access-key
shmemDir: /run/ospl
osplVersion: V6.10.4
