{{- if .Values.configfile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configfile
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.configfile.filename }}:
{{ .Values.configfile.content | toYaml | indent 4 }}
{{- end }}

