apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
