---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  path: {{ required "vaultPrefixPath must be set" .Values.vaultPrefixPath }}/ts/software/dbbbm
  type: Opaque
