image:
  repository: ts-dockerhub.lsst.org/love-producer
  tag: c0037
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  WEBSOCKET_HOST: love-nginx-service/love/manager/producers/ws/subscription
shmemDir: /run/ospl
producers:
  ataos: ATAOS:0
  atcamera: ATCamera:0
  atdome: ATDome:0
  atdometrajectory: ATDomeTrajectory:0
  atheaderservice: ATHeaderService:0
  athexapod: ATHexapod:0
  atmcs: ATMCS:0
  atpneumatics: ATPneumatics:0
  atocps: OCPS:1
  atoods: ATOODS:0
  atptg: ATPtg:0
  atscheduler: Scheduler:2
  atscriptqueue: ScriptQueue:2
  atspectrograph: ATSpectrograph:0
  auxteless201: ESS:201
  auxteless202: ESS:202
  auxteless203: ESS:203
  auxteless204: ESS:204
  auxteless205: ESS:205
  calibhilless301: ESS:301
  camerahexapod: MTHexapod:1
  cccamera: CCCamera:0
  ccheaderservice: CCHeaderService:0
  ccocps: OCPS:2
  ccoods: CCOODS:0
  dimm1: DIMM:1
  dimm2: DIMM:2
  dsm1: DSM:1
  dsm2: DSM:2
  epm1: EPM:1
  gcheaderservice1: GCHeaderService:1
  genericcamera1: GenericCamera:1
  lasertracker1: LaserTracker:1
  love: LOVE:0
  m2ess106: ESS:106
  m2hexapod: MTHexapod:2
  mtaircompressor1: MTAirCompressor:1
  mtaircompressor2: MTAirCompressor:2
  mtaos: MTAOS:0
  mtdome: MTDome:0
  mtdomeess101: ESS:101
  mtdomeess102: ESS:102
  mtdomeess103: ESS:103
  mtdomeess107: ESS:107
  mtdomeess108: ESS:108
  mtdometrajectory: MTDomeTrajectory:0
  mtm1m3: MTM1M3:0
  mtm2: MTM2:0
  mtmount: MTMount:0
  mtptg: MTPtg:0
  mtrotator: MTRotator:0
  mtscheduler: Scheduler:1
  mtscriptqueue: ScriptQueue:1
  ocsscheduler: Scheduler:3
  ocsscriptqueue: ScriptQueue:3
  tmaess001: ESS:1
  tmaess104: ESS:104
  tmaess105: ESS:105
  watcher: Watcher:0
  weatherforecast: WeatherForecast:0
osplVersion: V6.10.4
