image:
  repository: ts-dockerhub.lsst.org/ospl-daemon
  tag: c0039
  pullPolicy: Always
  nexus3: pull-secret
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
annotations:
  k8s.v1.cni.cncf.io/networks: kube-system/dds
shmemDir: /run/ospl
osplVersion: V6.10.4
