image:
  repository: ts-dockerhub.lsst.org/ospl-daemon
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
annotations:
  k8s.v1.cni.cncf.io/networks: kube-system/misc-dds
initContainer:
  repository: lsstit/ddsnet4u
  tag: latest
  pullPolicy: Always
shmemDir: /run/ospl
osplVersion: V6.10.4
