image:
  repository: ts-dockerhub.lsst.org/ospl-daemon
  tag: c0038
  pullPolicy: Always
  nexus3: pull-secret
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
shmemDir: /run/ospl
annotations:
  k8s.v1.cni.cncf.io/networks: kube-system/dds
osplVersion: V6.10.4
