namespace: obssys
image:
  repository: ts-dockerhub.lsst.org/watcher
  tag: c0039
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: base
  LSST_SITE: base
  OSPL_INFOFILE: /tmp/ospl-info-watcher.log
  OSPL_ERRORFILE: /tmp/ospl-error-watcher.log
shmemDir: /run/ospl
osplVersion: V6.10.4
