namespace: eas
image:
  repository: ts-dockerhub.lsst.org/eas
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-eascsc.log
  OSPL_ERRORFILE: /tmp/ospl-error-eascsc.log
  RUN_ARG: --simulate
shmemDir: /run/ospl
osplVersion: V6.10.4
