{{- $namespaces := keys .Values.secrets }}
{{- range $namespace := index $namespaces }}
{{- if not (eq (get $.Values.secrets $namespace) "") }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $namespace }}
  namespace: {{ $namespace }}
spec:
  path: {{ $.Values.vaultPathPrefix }}/{{ get $.Values.secrets $namespace }}
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
  namespace: {{ $namespace }}
spec:
  path: {{ $.Values.vaultPathPrefix }}/pull-secret
  type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
