namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/ptkernel
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  TELESCOPE: MT
  OSPL_INFOFILE: /tmp/ospl-info-mtptg.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtptg.log
shmemDir: /run/ospl
osplVersion: V6.10.4
