image:
  repository: ts-dockerhub.lsst.org/rapid-analysis
  tag: c0036
  pullPolicy: Always
location: BTS
siteTag: bts
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  DEPLOY_BRANCH: deploy-bts
scripts:
- name: summit/auxTel/runBackgroundService.py
  resources:
    requests:
      cpu: 0.5
      memory: 4G
    limits:
      cpu: 1.0
      memory: 10G
- name: summit/auxTel/runButlerWatcher.py
- name: summit/auxTel/runCalibrateCcdRunner.py
- name: summit/auxTel/runImExaminer.py
- name: summit/auxTel/runIsrRunner.py
- name: summit/auxTel/runMetadataCreator.py
- name: summit/auxTel/runMetadataServer.py
- name: summit/auxTel/runMonitor.py
  resources:
    requests:
      cpu: 0.5
      memory: 1G
    limits:
      cpu: 1.0
      memory: 10G
- name: summit/auxTel/runMountTorquePlotter.py
- name: summit/auxTel/runNightReporter.py
- name: summit/auxTel/runSpecExaminer.py
  resources:
    requests:
      cpu: 0.5
      memory: 2G
    limits:
      cpu: 1.0
      memory: 4G
- name: summit/misc/runTmaTelemetry.py
credentialFile: google_write_creds
vaultPrefixPath: secret/k8s_operator/base-lsp.lsst.codes
pullSecretsPath: pull-secret
rubinTvSecretsPath: ts/software/rubintv
credentialSecretsPath: ts/software/rubintv
butlerSecret:
  key: butler-secret
  containerPath: /home/saluser/.lsst
  dbUser: oods
imagePullSecrets:
- name: pull-secret
nfsMountpoint:
- name: auxtel-gen3-data
  containerPath: /repo/LATISS
  readOnly: false
  server: nfs-auxtel.ls.lsst.org
  serverPath: /auxtel/repo/LATISS
- name: auxtel-data
  containerPath: /readonly/lsstdata/auxtel
  readOnly: true
  server: nfs-auxtel.ls.lsst.org
  serverPath: /auxtel/lsstdata
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs-project.ls.lsst.org
  serverPath: /project
- name: auxtel-gen3-data-temp
  containerPath: /data/lsstdata/BTS/auxtel
  readOnly: true
  server: nfs-auxtel.ls.lsst.org
  serverPath: /auxtel/lsstdata/BTS/auxtel
- name: scratch-shared
  containerPath: /scratch
  readOnly: false
  server: nfs-scratch.ls.lsst.org
  serverPath: /scratch/rubintv
resources:
  requests:
    cpu: 0.5
    memory: 1G
  limits:
    cpu: 1.0
    memory: 2.5G
redis:
  enabled: true
  port: 6379
  env:
    MASTER: true
  envSecrets:
  - name: REDIS_PASSWORD
    secretName: rubintv-secrets
    secretKey: redis-password
  storage:
    classname: rook-ceph-block
    request: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 50Gi
