image:
  repository: ts-dockerhub.lsst.org/rapid-analysis
  tag: c0038
  pullPolicy: Always
location: SUMMIT
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
scripts:
- name: summit/auxTel/runBackgroundService.py
  resources:
    requests:
      cpu: 0.5
      memory: 4G
    limits:
      cpu: 1.0
      memory: 10G
- name: summit/auxTel/runButlerWatcher.py
- name: summit/auxTel/runCalibrateCcdRunner.py
- name: summit/auxTel/runImExaminer.py
- name: summit/auxTel/runIsrRunner.py
- name: summit/auxTel/runMetadataCreator.py
- name: summit/auxTel/runMetadataServer.py
- name: summit/auxTel/runMonitor.py
  resources:
    requests:
      cpu: 0.5
      memory: 1G
    limits:
      cpu: 1.0
      memory: 10G
- name: summit/auxTel/runMountTorquePlotter.py
- name: summit/auxTel/runNightReporter.py
- name: summit/auxTel/runSpecExaminer.py
  resources:
    requests:
      cpu: 0.5
      memory: 2G
    limits:
      cpu: 1.0
      memory: 4G
- name: summit/misc/runAllSky.py
  resources:
    requests:
      cpu: 1.0
      memory: 4G
    limits:
      cpu: 2
      memory: 6G
- name: summit/misc/runStarTracker.py
- name: summit/misc/runStarTrackerCatchup.py
- name: summit/misc/runStarTrackerFast.py
- name: summit/misc/runStarTrackerMetadata.py
- name: summit/misc/runStarTrackerNightReport.py
- name: summit/misc/runStarTrackerWide.py
- name: summit/misc/runTmaTelemetry.py
- name: summit/LSSTComCam/runButlerWatcher.py
- name: summit/LSSTComCam/runHeadNode.py
- name: summit/LSSTComCam/runMetadataServer.py
- name: summit/LSSTComCam/runPlotter.py
- name: summit/LSSTCam/runButlerWatcher.py
- name: summit/LSSTCam/runHeadNode.py
- name: summit/LSSTCam/runMetadataServer.py
- name: summit/LSSTCam/runPlotter.py
comcamWorkerSet:
  name: summit/LSSTComCam/runSfmRunner.py
  replicas: 36  # 4 deep
  resources:
    requests:
      cpu: 1.0
      memory: 4G
    limits:
      cpu: 1.0
      memory: 8G
comcamGather2aset:
  name: summit/LSSTComCam/runStep2aWorker.py
  replicas: 4  # 4 deep to match comcamWorkerSet
  resources:
    requests:
      cpu: 1.0
      memory: "4G"
    limits:
      cpu: 1.0
      memory: "8G"
comcamGatherRollupSet:
  name: summit/LSSTComCam/runNightlyWorker.py
  replicas: 2  # 2 is probably plenty, 1 might even be fine
  resources:
    requests:
      cpu: 1.0
      memory: "12G"
    limits:
      cpu: 1.0
      memory: "24G"
lsstcamWorkerSet:
  name: summit/LSSTCam/runSfmRunner.py
  replicas: 189  # 1 deep for now - in-focus chips only
  resources:
    requests:
      cpu: 1.0
      memory: 4G
    limits:
      cpu: 1.0
      memory: 8G  # we should check this value
credentialFile: google_write_creds
vaultPrefixPath: secret/k8s_operator/summit-lsp.lsst.codes
pullSecretsPath: pull-secret
rubinTvSecretsPath: ts/software/rubintv
credentialSecretsPath: rubintv-broadcaster
butlerSecret:
  key: butler-secret
  containerPath: /home/saluser/.lsst
  dbUser: oods
imagePullSecrets:
- name: pull-secret
nfsMountpoint:
- name: auxtel-gen3-data
  containerPath: /repo/LATISS
  readOnly: false
  server: nfs-auxtel.cp.lsst.org
  serverPath: /auxtel/repo/LATISS
- name: comcam-gen3-data
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.cp.lsst.org
  serverPath: /repo/LSSTComCam
- name: auxtel-data
  containerPath: /readonly/lsstdata/auxtel
  readOnly: true
  server: nfs-auxtel.cp.lsst.org
  serverPath: /auxtel/lsstdata
- name: comcam-data
  containerPath: /readonly/lsstdata/comcam
  readOnly: true
  server: comcam-archiver.cp.lsst.org
  serverPath: /lsstdata
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs1.cp.lsst.org
  serverPath: /project
- name: auxtel-gen3-data-temp
  containerPath: /data/lsstdata/base/auxtel
  readOnly: true
  server: nfs-auxtel.cp.lsst.org
  serverPath: /auxtel/lsstdata/base/auxtel
- name: comcam-gen3-data-temp
  containerPath: /data/lsstdata/base/comcam
  readOnly: true
  server: comcam-archiver.cp.lsst.org
  serverPath: /lsstdata/base/comcam
- name: allsky-data
  containerPath: /data/allsky
  readOnly: true
  server: nfs-auxtel.cp.lsst.org
  serverPath: /auxtel/allsky
- name: scratch-shared
  containerPath: /scratch
  readOnly: false
  server: nfs1.cp.lsst.org
  serverPath: /scratch/rubintv
resources:
  requests:
    cpu: 0.5
    memory: 1G
  limits:
    cpu: 1.0
    memory: 2.5G
redis:
  enabled: true
  port: 6379
  env:
    MASTER: true
  envSecrets:
  - name: REDIS_PASSWORD
    secretName: rubintv-secrets
    secretKey: redis-password
  storage:
    classname: rook-ceph-block
    request: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 50Gi
