namespace: auxtel
image:
  repository: ts-dockerhub.lsst.org/atoods
  tag: c0031-fsfix
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  OSPL_INFOFILE: /tmp/ospl-info-atoods.log
  OSPL_ERRORFILE: /tmp/ospl-error-atoods.log
  CTRL_OODS_CONFIG_FILE: /etc/atoods.yaml
shmemDir: /run/ospl
osplVersion: V6.10.4
butlerSecret:
  containerPath: &bS-cP /home/saluser/.lsst
  dbUser: oods
secretPermFixer:
- name: butler-secret
  containerPath: *bS-cP
nfsMountpoint:
- name: auxtel-gen3-butler
  containerPath: /repo/LATISS
  readOnly: false
  server: nfs-auxtel.tu.lsst.org
  serverPath: /auxtel/repo/LATISS
- name: auxtel-oods-data
  containerPath: /data
  readOnly: false
  server: nfs-auxtel.tu.lsst.org
  serverPath: /auxtel
configfile:
  path: /etc
  filename: atoods.yaml
  content: |
    defaultInterval: &interval
        days: 0
        hours: 0
        minutes: 0
        seconds: 0

    ingester:
        imageStagingDirectory: /data/staging/auxtel/oods
        butlers:
            - butler:
                instrument: lsst.obs.lsst.Latiss
                class:
                    import : lsst.ctrl.oods.gen3ButlerIngester
                    name : Gen3ButlerIngester
                stagingDirectory : /data/lsstdata/TTS/auxtel/oods/gen3butler/raw
                badFileDirectory: /data/lsstdata/TTS/auxtel/oods/gen3butler/badfiles
                repoDirectory : /repo/LATISS
                collections:
                    - LATISS/raw/all
                scanInterval:
                    <<: *interval
                    hours: 1
                filesOlderThan:
                    <<: *interval
                    days: 30
        batchSize: 20
        scanInterval:
            <<: *interval
            seconds: 2

    cacheCleaner:
        # ONLY clean out empty directories here, never files
        clearEmptyDirectories:
            - /data/lsstdata/TTS/auxtel/oods/gen3butler/raw
        # clean out empty directories and old files from these directories
        clearEmptyDirectoriesAndOldFiles:
            - /data/lsstdata/TTS/auxtel/oods/gen3butler/badfiles
            - /data/staging/auxtel/oods
            - /data/staging/auxtel/forwarder
        scanInterval:
            <<: *interval
            hours: 1
        filesOlderThan:
            <<: *interval
            days: 31
        directoriesEmptyForMoreThan:
            <<: *interval
            days: 2
