namespace: eas
image:
  repository: ts-dockerhub.lsst.org/dimm
  tag: c0037
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-dimm.log
  OSPL_ERRORFILE: /tmp/ospl-error-dimm.log
shmemDir: /run/ospl
osplVersion: V6.10.4
