image:
  repository: ts-dockerhub.lsst.org/salkafka
  tag: c0038
  pullPolicy: Always
  nexus3: pull-secret
env:
  lsstDdsPartitionPrefix: tucson
  brokerIp: sasquatch-kafka-brokers.sasquatch
  brokerPort: 9092
  registryAddr: http://sasquatch-schema-registry.sasquatch:8081
  partitions: 1
  replication: 3
  waitAck: 1
  logLevel: 20
  extras:
    LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
    TS_SALKAFKA_USERNAME: ts-salkafka
shmemDir: /run/ospl
osplVersion: V6.10.4
producers:
  auxtel:
    cscs: >-
      ATAOS
      ATDome
      ATDomeTrajectory
      ATHexapod
      ATPneumatics
      ATPtg
      ATMCS
  comcam:
    cscs: CCCamera CCHeaderService CCOODS
  maintel:
    cscs: >-
      MTAOS
      MTDome
      MTDomeTrajectory
      MTPtg
  mtmount:
    cscs: >-
      MTMount
  latiss:
    cscs: >-
      ATCamera
      ATHeaderService
      ATOODS
      ATSpectrograph
  m1m3:
    cscs: >-
      --file m1m3.yaml
  m2:
    cscs: >-
      MTHexapod
      MTM2
      MTRotator
  obssys:
    cscs: >-
      Scheduler
      Script
      ScriptQueue
      Watcher
  ocps:
    cscs: >-
      OCPS
  test:
    cscs: >-
      Test
  calsys:
    cscs: >-
      CBP
      Electrometer
      FiberSpectrograph
      LEDProjector
      LinearStage
      TunableLaser
  mtaircompressor:
    cscs: MTAirCompressor
  eas:
    cscs: DIMM DSM EPM ESS WeatherForecast
  lasertracker:
    cscs: LaserTracker
  genericcamera:
    cscs: GCHeaderService GenericCamera
existingSecret: kafka-producers
startupProbe:
  use: true
  failureThreshold: 15
  initialDelay: 20
  period: 10
