image:
  repository: ts-dockerhub.lsst.org/salkafka
  tag: c0039
  pullPolicy: Always
  nexus3: pull-secret
env:
  lsstDdsPartitionPrefix: summit
  brokerIp: sasquatch-kafka-brokers.sasquatch
  brokerPort: 9092
  registryAddr: http://sasquatch-schema-registry.sasquatch:8081
  partitions: 1
  replication: 3
  waitAck: 1
  logLevel: 20
  extras:
    LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
    TS_SALKAFKA_USERNAME: ts-salkafka
shmemDir: /run/ospl
osplVersion: V6.10.4
producers:
  auxtel:
    cscs: >-
      ATAOS
      ATBuilding
      ATDome
      ATDomeTrajectory
      ATHexapod
      ATPneumatics
      ATPtg
      ATMCS
  maintel:
    cscs: >-
      MTAOS
      MTDome
      MTDomeTrajectory
      MTPtg
  mtmount:
    cscs: >-
      MTMount
  comcam:
    cscs: >-
      CCCamera
      CCHeaderService
      CCOODS
  eas:
    cscs: >-
      DIMM
      DREAM
      DSM
      EAS
      EPM
      ESS
      HVAC
      WeatherForecast
  latiss:
    cscs: >-
      ATCamera
      ATHeaderService
      ATOODS
      ATSpectrograph
  m1m3:
    cscs: >-
      --file m1m3.yaml
  m2:
    cscs: >-
      MTHexapod
      MTM2
      MTRotator
  obssys:
    cscs: >-
      Scheduler
      Script
      ScriptQueue
      Watcher
  ocps:
    cscs: >-
      OCPS
  test:
    cscs: >-
      Test
  pmd:
    cscs: >-
      PMD
  calsys:
    cscs: >-
      ATMonochromator
      ATWhiteLight
      CBP
      Electrometer
      FiberSpectrograph
      LEDProjector
      LinearStage
      TunableLaser
  mtaircompressor:
    cscs: MTAirCompressor
  m1m3ts:
    cscs: MTM1M3TS
  genericcamera:
    cscs: GCHeaderService GenericCamera
  gis:
    cscs: GIS
  mtvms:
    cscs: MTVMS
  lasertracker:
    cscs: LaserTracker
  lsstcam:
    cscs: MTCamera MTHeaderService MTOODS
existingSecret: kafka-producers
startupProbe:
  use: true
  failureThreshold: 15
  initialDelay: 20
  period: 10
