image:
  repository: ts-dockerhub.lsst.org/salkafka
  tag: c0032
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  lsstDdsPartitionPrefix: tucson
  brokerIp: sasquatch-kafka-brokers.sasquatch
  brokerPort: 9092
  registryAddr: http://sasquatch-schema-registry.sasquatch:8081
  partitions: 1
  replication: 3
  waitAck: 1
  logLevel: 20
  extras:
    LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
    TS_SALKAFKA_USERNAME: ts-salkafka
shmemDir: /run/ospl
osplVersion: V6.10.4
producers:
  calsys:
    cscs: >-
      CBP
      Electrometer
      FiberSpectrograph
      LinearStage
      TunableLaser
existingSecret: kafka-producers-ts-salkafka
startupProbe:
  use: true
  failureThreshold: 15
  initialDelay: 20
  period: 10
