namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/headerservice
  tag: c0037
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
  URL_SPEC: --lfa_mode s3 --s3instance cp --playback
  S3_ENDPOINT_URL: https://s3.cp.lsst.org
  CAMERA: cc
  OSPL_INFOFILE: /tmp/ospl-info-ccheaderservice.log
  OSPL_ERRORFILE: /tmp/ospl-error-ccheaderservice.log
  HEADERSERVICE_PLAYLIST_DIR: /net/self/ccs-data/cchs-sim
envSecrets:
- name: AWS_ACCESS_KEY_ID
  secretName: lfa
  secretKey: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  secretName: lfa
  secretKey: aws-secret-access-key
- name: MYS3_ACCESS_KEY
  secretName: lfa
  secretKey: aws-access-key-id
- name: MYS3_SECRET_KEY
  secretName: lfa
  secretKey: aws-secret-access-key
nfsMountpoint:
- name: ccs-data
  containerPath: /net/self/ccs-data
  readOnly: true
  server: comcam-fp01.cp.lsst.org
  serverPath: /ccs-data
shmemDir: /run/ospl
osplVersion: V6.10.4
