namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/headerservice
  tag: c0039
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
  URL_SPEC: --lfa_mode s3 --s3instance cp --playback
  S3_ENDPOINT_URL: https://s3.cp.lsst.org
  CAMERA: cc
  OSPL_INFOFILE: /tmp/ospl-info-ccheaderservice.log
  OSPL_ERRORFILE: /tmp/ospl-error-ccheaderservice.log
  HEADERSERVICE_PLAYLIST_DIR: /header_service
envSecrets:
- name: AWS_ACCESS_KEY_ID
  secretKey: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  secretKey: aws-secret-access-key
- name: MYS3_ACCESS_KEY
  secretKey: aws-access-key-id
- name: MYS3_SECRET_KEY
  secretKey: aws-secret-access-key
nfsMountpoint:
- name: ccs-data
  containerPath: /header_service
  readOnly: true
  server: nfs1.cp.lsst.org
  serverPath: /scratch/header_service
shmemDir: /run/ospl
osplVersion: V6.10.4
