namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/mtm1m3_sim
  tag: c0038
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-mtm1m3.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtm1m3.log
  OSPL_RELEASE: v6.10.4
shmemDir: /run/ospl
osplVersion: V6.10.4
