namespace: auxtel
image:
  repository: ts-dockerhub.lsst.org/ptkernel
  tag: c0037
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  TELESCOPE: AT
  OSPL_INFOFILE: /tmp/ospl-info-atptg.log
  OSPL_ERRORFILE: /tmp/ospl-error-atptg.log
shmemDir: /run/ospl
osplVersion: V6.10.4
