namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/mtdometrajectory
  tag: c0037
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-mtdometrajectory.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtdometrajectory.log
shmemDir: /run/ospl
osplVersion: V6.10.4
