namespace: auxtel
image:
  repository: ts-dockerhub.lsst.org/at_pneumatics_sim
  tag: c0038
  pullPolicy: Always
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-atpneumatics.log
  OSPL_ERRORFILE: /tmp/ospl-error-atpneumatics.log
shmemDir: /run/ospl
osplVersion: V6.10.4
