apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-test-controller-configmap
  labels:
    # Note that this label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  artifactRepository: |    # However, all nested maps must be strings
    s3:
      endpoint: {{ .Values.s3Endpoint }}
      bucket: {{ .Values.s3Bucket }}
      insecure: false
      accessKeySecret:
        name: {{ .Values.namespace }}
        key: aws-access-key-id
      secretKeySecret:
        name: {{ .Values.namespace }}
        key: aws-secret-access-key
